### ISSUE TITLE
database

### ISSUE THREAD

**Issue by galengold** [young-amateurs-rc/YARL#7]
database backend

**Comment by galengold** [comment]
maybe use ADIF files instead? more portable, but harder to query/update/etc.

http://adif.org/308/ADIF_308.htm

**Comment by galengold** [comment]
Connect to local/remote MySQL/MariaDB server via URL (e.g. localhost:_port_/whatever or _server:port_/whatever). Not sure how this would work on windows (maybe see http://www.w4rp.com/update_by_w4rp.pdf)

**Comment by dargasea** [comment]
Must we use a daemon-based database instead of something file-based like SQLite?

I would hope that a logger is something that works mostly out-of-the-box. Having to setup MariaDB -- even if a user already has an instance on their system -- probably defeats this purpose.

**Comment by galengold** [comment]
yeah, good idea. I've had the most experience with MySQL/MariaDB, but I was definitely looking for a self-contained solution

**Comment by galengold** [comment]
https://pysqlite.readthedocs.io/en/latest/sqlite3.html

**Comment by cschmittiey** [comment]
I totally support both -- if the time comes that we need a bigger, more
powerful db.  However, I think we probably ought to start out with just
SQLlite

**Comment by galengold** [comment]
Yeah, I like the idea of being able to store my log database on my server, then connecting to it on whatever computer I'm using, so we could include support for SQLite and MySQL, but that's for another time

**Comment by dargasea** [comment]
Totally doable. Use an OEM like SQLalchemy for Python and the DB back end can be flexible.

**Comment by galengold** [comment]
TODO Galen: make the table creation its own function, which can be called from `__init__` (maybe if optional args exist?)

**Comment by galengold** [comment]
TODO Galen: add update entry funciton

**Comment by galengold** [comment]
TODO Galen: use dicts less

**Comment by galengold** [comment]
Merged #29
